openapi: 3.0.0
info:
  title: API for the lecture feedback collector
  description: Offers collecting realtime feedback during a lecture. Creates sessions where feedback can be captured and then analysed
  version: 0.0.0

paths:
  /sessions:
    post:
      summary: Creates a new session with the given parameters
      requestBody:
        description: Outlines the parameters that the session will have
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sessionCreationRequest'
          application/yaml:
            schema:
              $ref: '#/components/schemas/sessionCreationRequest'
      responses:
        '200':
          description: Session created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/session'
            application/yaml:
              schema:
                $ref: '#/components/schemas/session'
        '400':
          description: An error has occurred. The message will outline the error, but it is likely that the user does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
            application/yaml:
              schema:
                $ref: '#/components/schemas/error'
    get:
      summary: Returns all the sessions that have been created by a specific user
      description: Returns an array with details of all the sessions that have been created by a user
      responses:
        '200':
          description: Sessions returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/session'
      
components:
  schemas:
    sessionCreationRequest:
      type: object
      properties:
        name:
          type: string
        user:
          type: string
      required:
        - name
        - user
    session:
      type: object
      properties:
        name:
          type: string
        user:
          type: string
        active:
          type: boolean
        timestamp:
          type: integer
        accessCode:
          type: string
      required:
        - name
        - user
        - active
        - timestamp

    error:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
        - description


